apiVersion: v1
kind: Pod
metadata:
  name: myfirstpod3
  labels:
    app: myApp
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 8082
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"