apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
type: Opaque
data:
  WORDPRESS_DB_HOST: bXlzcWw=
  WORDPRESS_DB_USER: ZXhhbXBsZXVzZXI=
  WORDPRESS_DB_PASSWORD: ZXhhbXBsZXBhc3N3b3Jk
  WORDPRESS_DB_NAME: ZXhhbXBsZWRi

