apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql-service
spec:
  ports:
  - port: 3306
    name: db
  type: ClusterIP
  selector:
    app: mysql

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress-service
spec:
  ports:
    - port: 80
      name: wordpress
      targetPort: 80
  type: ClusterIP
  selector:
    app: wordpress