apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-app
  labels:
    app: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-mysql
  serviceName: "mysql-service"
  template:
    metadata:
      labels:
        app: backend-mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysql
          image: mysql
          ports:
            - containerPort: 3306
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: mysql-secret
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: mysql-secret
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: MYSQL_DATABASE
                  name: mysql-secret
          volumeMounts:
            - name: db
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: db
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 500Mi