apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-app
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-wordpress
  template:
    metadata:
      labels:
        app: frontend-wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:php8.2-fpm-alpine
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              valueFrom:
                secretKeyRef:
                  key: WORDPRESS_DB_HOST
                  name: wordpress-secret
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  key: WORDPRESS_DB_USER
                  name: wordpress-secret
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: WORDPRESS_DB_PASSWORD
                  name: wordpress-secret
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  key: WORDPRESS_DB_NAME
                  name: wordpress-secret